---
title: "R Notebook"
output: html_notebook
---

Project 
https://www.drivendata.org/competitions/51/electricity-prediction-machine-learning/page/101/#metric

```{r}

library(dplyr); library(readr); library(stringr)
sub_freq <- read.csv("C:/Users/Meghan Clark/Desktop/Machine Learning/energy data/submission_frequency.csv")
#ids: ForecastId, ForecastPeriodNS
#6974 rows

sub_format <- read.csv("C:/Users/Meghan Clark/Desktop/Machine Learning/energy data/submission_format.csv")
#ids: obs_id, SiteId, Timestamp, ForecastId, Value
#1,309,176 rows

metadata <- read.csv("C:/Users/Meghan Clark/Desktop/Machine Learning/energy data/metadata.csv")
#ids: SiteID, Surface, Sampling, BaseTemperature, MondayIsDayOff, TuesdayIsDayOff, WednesdayIsDayOff, ThursdayIsDayOff, FridayIsDayOff, SaturdayIsDayOff, SundayIsDayOff
#267 rows

holidays <- read.csv("C:/Users/Meghan Clark/Desktop/Machine Learning/energy data/holidays.csv")
#ids: X, Date, Holiday, SiteId
#8387 rows

train <- read.csv("C:/Users/Meghan Clark/Desktop/Machine Learning/energy data/train.csv")
#ids: obs_id (timestamp), SiteId (305), Timestamp, ForecastId, Value
#6,559,830 rows

weather <- read.csv("C:/Users/Meghan Clark/Desktop/Machine Learning/energy data/weather.csv")

```
Select the data for SiteID 1

```{r}


sub_format$Timestamp <- as.character(sub_format$Timestamp) %>% str_sub(., 1, str_length(.)-9)
holidays$Holiday <- "TRUE"
colnames(holidays)[2] <- "Timestamp"
holidays$Timestamp <- as.character(holidays$Timestamp)
holidays2 <- holidays %>% select(c("Timestamp", "Holiday", "SiteId")) %>% distinct()
formatholiday <- right_join(holidays2, sub_format, by = c( "Timestamp", "SiteId" )) 

formatholiday$Day <- weekdays(as.Date(formatholiday$Timestamp))


#Divide by Day Join by SiteId and keep IsXDayXOff 
msubformat <- formatholiday %>% subset(Day == "Monday")
mmetadata <- metadata %>% select(c(SiteId, MondayIsDayOff))
msubformat2 <- left_join(msubformat, mmetadata)
colnames(msubformat2)[8] <- "Closed"

tsubformat <- formatholiday %>% subset(Day == "Tuesday")
tmetadata <- metadata %>% select(c(SiteId, TuesdayIsDayOff))
tsubformat2 <- left_join(tsubformat, tmetadata)
colnames(tsubformat2)[8] <- "Closed"

wsubformat <- formatholiday %>% subset(Day == "Wednesday")
wmetadata <- metadata %>% select(c(SiteId, WednesdayIsDayOff))
wsubformat2 <- left_join(wsubformat, wmetadata)
colnames(wsubformat2)[8] <- "Closed"

thsubformat <- formatholiday %>% subset(Day == "Thursday")
thmetadata <- metadata %>% select(c(SiteId, ThursdayIsDayOff))
thsubformat2 <- left_join(thsubformat, thmetadata)
colnames(thsubformat2)[8] <- "Closed"

fsubformat <- formatholiday %>% subset(Day =="Friday")
fmetadata <- metadata %>% select(c(SiteId, FridayIsDayOff))
fsubformat2 <- left_join(fsubformat, fmetadata)
colnames(fsubformat2)[8] <- "Closed"

ssubformat <- formatholiday %>% subset(Day =="Saturday")
smetadata <- metadata %>% select(c(SiteId, FridayIsDayOff))
ssubformat2 <- left_join(ssubformat, smetadata)
colnames(ssubformat2)[8] <- "Closed"

sunsubformat <- formatholiday %>% subset(Day == "Sunday")
sunmetadata <- metadata %>% select(c(SiteId, FridayIsDayOff))
sunsubformat2 <- left_join(sunsubformat, sunmetadata)
colnames(sunsubformat2)[8] <- "Closed"

xmatrix <- rbind(msubformat2, tsubformat2, wsubformat2, thsubformat2, fsubformat2, ssubformat2, sunsubformat2)
xmatrix <- as.data.frame(xmatrix)

write.csv(xmatrix, 'xmatrix.csv')
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
